import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'public', 'fonts');
fs.mkdirSync(outDir, { recursive: true });

// Trimmed to the weight ranges this site actually renders.
// Google Fonts serves these as variable fonts, so each family is ONE woff2 file
// covering the whole range - no per-weight duplicates.
const FAMILIES = [
  { css: 'Cinzel:wght@400;600' },
  { css: 'Inter:wght@300;400;500;600' },
  { css: 'JetBrains+Mono:wght@400;500' },
];

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const url =
  'https://fonts.googleapis.com/css2?' +
  FAMILIES.map((f) => `family=${f.css}`).join('&') +
  '&display=swap';

const res = await fetch(url, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`Google Fonts CSS failed: ${res.status}`);
const css = await res.text();

// Keep only the plain `/* latin */` blocks (skip latin-ext, cyrillic, greek, vietnamese).
const byFamily = new Map();

for (const block of css.split('/*').slice(1)) {
  const subset = block.slice(0, block.indexOf('*/')).trim();
  if (subset !== 'latin') continue;
  const body = block.slice(block.indexOf('*/') + 2);
  const family = /font-family: '([^']+)'/.exec(body)?.[1];
  const weight = Number(/font-weight: (\d+)/.exec(body)?.[1]);
  const src = /url\((https:[^)]+\.woff2)\)/.exec(body)?.[1];
  const range = /unicode-range: ([^;]+);/.exec(body)?.[1];
  if (!family || !weight || !src) continue;

  const entry = byFamily.get(family) ?? { src, range, min: weight, max: weight };
  entry.min = Math.min(entry.min, weight);
  entry.max = Math.max(entry.max, weight);
  byFamily.set(family, entry);
}

const kept = [];
let total = 0;

for (const [family, entry] of byFamily) {
  const slug = family.toLowerCase().replace(/\s+/g, '-');
  const file = `${slug}-variable.woff2`;
  const bin = await fetch(entry.src, { headers: { 'User-Agent': UA } });
  if (!bin.ok) throw new Error(`woff2 fetch failed ${entry.src}: ${bin.status}`);
  const buf = Buffer.from(await bin.arrayBuffer());
  fs.writeFileSync(path.join(outDir, file), buf);
  total += buf.length;
  console.log(`  ${file.padEnd(28)} ${String(buf.length).padStart(6)} bytes  weights ${entry.min}-${entry.max}`);

  kept.push(
    [
      '@font-face {',
      `  font-family: '${family}';`,
      '  font-style: normal;',
      `  font-weight: ${entry.min} ${entry.max};`,
      '  font-display: swap;',
      `  src: url('/fonts/${file}') format('woff2-variations');`,
      entry.range ? `  unicode-range: ${entry.range};` : null,
      '}',
    ]
      .filter(Boolean)
      .join('\n')
  );
}

const header =
  '/* Self-hosted latin subsets of Cinzel, Inter and JetBrains Mono (variable woff2).\n' +
  '   Generated by scripts/fetch-fonts.mjs - regenerate with: node scripts/fetch-fonts.mjs */\n\n';
fs.writeFileSync(path.join(outDir, 'fonts.css'), header + kept.join('\n\n') + '\n');
console.log(`\nwrote public/fonts/fonts.css - ${byFamily.size} families, ${total} bytes total`);
